import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import RecoilContextProvider from './recoilContextProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'APPOR Portal',
  description: 'Generated by APPOR Portal',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}> <RecoilContextProvider>{children}</RecoilContextProvider></body>
    </html>
  )
}
